---
title: "Veraverbeke Clean data to point"
author: "Anna Talucci"
date: '2022-12-02'
output: html_document
---


# clear environment
```{r}
rm(list=ls())
```

# Overview

Adapt script form M. Loranty data_cleaning, to only clean and not aggregate data. 

Use data from csv files in Google Drive

What this script does:


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```
# Projection

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

# Data

# vector of data files
```{r}
f <- list.files(path = "../data/GoogleDriveCsvFolder/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```



## Veraverbeke
```{r}
f16 <- read.csv(f[16], header = TRUE)
f16
```
```{r}
str(f16)
```
# fix incorrect logical columns
```{r}
f16$thaw_active <- read.csv(f[16], header = TRUE, colClasses = "character")[,19]
```

```{r}
f16_dates = f16 %>%
  mutate(date = as.Date(with(., paste(year, month, day,sep="-")), "%Y-%m-%d")) %>%
  mutate(julianDate = yday(date)) %>%
  drop_na((lat))

f16_dates
```

```{r}
f16_dates %>% distinct(site_id, plot_id, fire_id, burn_unburn) %>% write.csv(., '../outputs/pairs/veraverbeke.csv')
```
```{r}
f16_dates %>% distinct(julianDate, year, date)
```


# Finish cleaning to match other datasets
```{r}
( 
  f16_clean = f16_dates %>%  
  mutate(across(c(plot_id, site_id, fire_id), as.character)) %>% 
  mutate(across(c(fire_year, organic_depth, slope, day), as.numeric)) %>% 
    mutate(across(day, ~coalesce(., 0))) %>%
  rename(lastNm = last_name, cntryId = country_code, lon=long, biome=boreal_tundra, vegCC = veg_cover_class, siteId = site_id, plotId = plot_id, fireId = fire_id, fireYr = fire_year, distur = burn_unburn, orgDpth = organic_depth, msrDepth = thaw_depth, hitRock=hit_rock, gtProbe = gt_probe, msrType = thaw_active, topoPos = topo_position, jDate = julianDate) %>%
    mutate(msrType = as.character(msrType))
)
```

# Create points shapefile

```{r}
f16_pts = st_as_sf(f16_clean, coords = c("lon","lat"), crs = 4326, remove = FALSE)
```


### write to shapefile
```{r}
st_write(f16_pts, "../outputs/allPoints/Veraverbeke_pts.shp", driver="ESRI Shapefile")
```