---
title: "Frost Clean to Point"
author: "Anna Talucci"
date: '2022-12-11'
output: html_document
---

# clear environment
```{r}
rm(list=ls())
```

# Overview
**MISSING DAY OF MONTH**
Adapt script form M. Loranty data_cleaning, to only clean and not aggregate data. 

Use data from csv files in Google Drive

What this script does:


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```
# Projection

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

# Data

# vector of data files
```{r}
f <- list.files(path = "../data/GoogleDriveCsvFolder/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```



## Frost
```{r}
f6 <- read.csv(f[6], header = TRUE)
f6
```
```{r}
str(f6)
```

```{r}
f6$thaw_active <- read.csv(f[6], header = TRUE, colClasses = "character")[,19]
```

```{r}
f6_dates = f6 %>%
  mutate(date = as.Date(with(., paste(year, month, day,sep="-")), "%Y-%m-%d")) %>%
  mutate(julianDate = yday(date)) %>%
  drop_na(.)

f6_dates
```



```{r}
f6_dates %>% distinct(julianDate, year, date)
```

# Create points shapefile

## For F6
sf::st_as_sf(dd, coords = c("x","y"))
```{r}
f6_pts = st_as_sf(f6_dates, coords = c("long","lat"), crs = 4326, remove = FALSE)
```


### write to shapefile
```{r}
st_write(f6_pts, "../outputs/AdjustedALT/Frost_points.shp", driver="ESRI Shapefile")
```