---
title: "Gaglioti Clean to Point"
author: "Anna Talucci"
date: '2022-12-11'
output: html_document
---


# clear environment
```{r}
rm(list=ls())
```

# Overview

Adapt script form M. Loranty data_cleaning, to only clean and not aggregate data. 

Use data from csv files in Google Drive

What this script does:


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```
# Projection

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

# Data

# vector of data files
```{r}
f <- list.files(path = "../data/GoogleDriveCsvFolder/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```



## Gaglioti

```{r}
f7 <- read.csv(f[7], header = TRUE)
f7
```


```{r}
# set gt_probe
f7$gt_probe <- "n"

# organic depth is missing, but set to NA
f7$organic_depth <- as.numeric(f7$organic_depth)
```

```{r}
str(f7)
```

```{r}
f7_dates = f7 %>%
  mutate(date = as.Date(with(., paste(year, month, day,sep="-")), "%Y-%m-%d")) %>%
  mutate(julianDate = yday(date)) %>%
  dplyr::select(-Notes) 

f7_dates
```





```{r}
f7_dates %>% distinct(julianDate, year, date)
```

# Split by active & thaw
```{r}
f7_thaw = f7_dates %>% 
  filter(thaw_active == "T") 

f7_thaw

f7_active = f7_dates %>% 
  filter(thaw_active == "A") 

f7_active
```

# Create points shapefile

## For F7
sf::st_as_sf(dd, coords = c("x","y"))
```{r}
f7_active_pts = st_as_sf(f7_active, coords = c("long","lat"), crs = 4326, remove = FALSE)
```

```{r}
f7_pts = st_as_sf(f7_dates, coords = c("long","lat"), crs = 4326, remove = FALSE)
```


### write to shapefile
```{r eval=FALSE, include=FALSE}
st_write(f7_active_pts, "../outputs/ActivePoints/Gaglioti_active_pts.shp", driver="ESRI Shapefile")
```

```{r}
st_write(f7_pts, "../outputs/allPoints/Gaglioti_pts.shp", driver="ESRI Shapefile")
```