---
title: " O'Donnell Clean to Point"
author: "Anna Talucci"
date: '2022-12-11'
output: html_document
---


# clear environment
```{r}
rm(list=ls())
```

# Overview

Adapt script form M. Loranty data_cleaning, to only clean and not aggregate data. 

Use data from csv files in Google Drive

What this script does:


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```
# Projection

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

# Data

# vector of data files
```{r}
f <- list.files(path = "../data/GoogleDriveCsvFolder/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```



## O'Donnell
```{r}
f10 <- read.csv(f[10], header = TRUE)
f10
```
```{r}
str(f10)
```
# fix incorrect logical columns
```{r}
f10$organic_depth <- as.numeric(gsub(">", "",f10$organic_depth))

f10$thaw_depth <- as.numeric(gsub(">", "",f10$thaw_depth))

f10 %>% distinct(site_id,year,month,day,fire_id,burn_unburn)

```

```{r}
f10_dates = f10 %>%
  mutate(date = as.Date(with(., paste(year, month, day,sep="-")), "%Y-%m-%d")) %>%
  mutate(julianDate = yday(date))

f10_dates
```


```{r}
f10_dates %>% distinct(julianDate, year, date)
```

# Create points shapefile

## For F10
sf::st_as_sf(dd, coords = c("x","y"))
```{r}
f10_pts = st_as_sf(f10_dates, coords = c("long","lat"), crs = 4326, remove = FALSE)
```


### write to shapefile
```{r}
st_write(f10_pts, "../outputs/AdjustedALT/ODonnell_points.shp", driver="ESRI Shapefile")
```
