---
title: "Sizov Clean To Point"
author: "Anna Talucci"
date: '2022-12-11'
output: html_document
---




# clear environment
```{r}
rm(list=ls())
```

# Overview

Adapt script form M. Loranty data_cleaning, to only clean and not aggregate data. 

Use data from csv files in Google Drive

What this script does:


# Packages

```{r}
library(tidyverse)
library(lubridate)
library(sf)
```
# Projection

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

# Data

# vector of data files
```{r}
f <- list.files(path = "../data/GoogleDriveCsvFolder/",
                pattern = "*.csv", full.names = TRUE)
```

```{r}
f
```



## Sizov
```{r}
f14 <- read.csv(f[14], header = TRUE)
f14
```
```{r}
str(f14)
```


```{r}
f14_dates = f14 %>%
  mutate(date = as.Date(with(., paste(year, month, day,sep="-")), "%Y-%m-%d")) %>%
  mutate(julianDate = yday(date)) %>%
  dplyr::select(-notes)

f14_dates
```


```{r}
f14_dates %>% distinct(site_id, plot_id, fire_id, burn_unburn) %>% write.csv(., '../outputs/pairs/sizov.csv')
```
```{r}
f14_dates %>% distinct(julianDate, year, date)
```

# Split by active & thaw
```{r}
f14_thaw = f14_dates %>% 
  filter(thaw_active == "T") 

f14_thaw

f14_active = f14_dates %>% 
  filter(thaw_active == "A") 

f14_active
```

# Create points shapefile

## For F14
sf::st_as_sf(dd, coords = c("x","y"))
```{r}
f14_active_pts = st_as_sf(f14_active, coords = c("long","lat"), crs = 4326, remove = FALSE)
f14_pts = st_as_sf(f14_dates, coords = c("long","lat"), crs = 4326, remove = FALSE)
```


### write to shapefile
```{r}
st_write(f14_active_pts, "../outputs/ActivePoints/Sizov_active_pts.shp", driver="ESRI Shapefile")
st_write(f14_pts, "../outputs/allPoints/Sizov_pts.shp", driver="ESRI Shapefile")
```